{
 "title": "MyBudget - Yearly",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "expense_type",
    "label": "Expense Type",
    "query": "SELECT expense_type FROM dbo.expense_types"
   },
   {
    "name": "loan",
    "label": "loan",
    "query": "SELECT loan_alias FROM dbo.loans"
   },
   {
    "name": "insurance",
    "label": "Insurance",
    "query": "SELECT insurance_alias FROM dbo.insurance"
   },
   {
    "name": "tuition",
    "label": "Tuition",
    "query": "SELECT tuition_alias FROM dbo.tuition"
   }
  ]
 },
 "panels": [
  {
   "title": "Income",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, 1, 1 ) as time,\n  SUM(amount) as value,\n  'Andy' as metric\nFROM\n  income\nWHERE\n  family_member_id = 3 AND DATEFROMPARTS ( year_id, 1, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  year_id,\n  DATEFROMPARTS ( year_id, 1, 1 )\nORDER BY\n  time ASC"
    },
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, 1, 1 ) as time,\n  SUM(amount) as value,\n  'Katie' as metric\nFROM\n  income\nWHERE\n  family_member_id = 4 AND DATEFROMPARTS ( year_id, 1, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  year_id,\n  DATEFROMPARTS ( year_id, 1, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Expenses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, 1, 1 ) as time,\n  SUM(amount) as value,\n  'Expenses' as metric\nFROM\n  expenses\nWHERE\n  DATEFROMPARTS ( year_id, 1, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  year_id,\n  DATEFROMPARTS ( year_id, 1, 1 )\nORDER BY\n  time ASC"
    },
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, 1, 1 ) as time,\n  SUM(amount) as value,\n  'Payments' as metric\nFROM\n  payments\nWHERE\n  DATEFROMPARTS ( year_id, 1, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  year_id,\n  DATEFROMPARTS ( year_id, 1, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Excess",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "rawSql": "SELECT DATEFROMPARTS ( year_id, 1, 1 ) as time,\r\n       SUM(income) - (SUM(expenses) + SUM(payments)) AS Excess\r\nFROM     dbo.View_Totals\r\nWHERE\r\n  DATEFROMPARTS ( year_id, 1, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY \r\n  year_id,\r\n  DATEFROMPARTS ( year_id, 1, 1 )\r\nORDER BY\r\n  time ASC"
    }
   ]
  },
  {
   "title": "Excess Percentage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT DATEFROMPARTS ( year_id, 1, 1 ) as time,\r\n       (SUM(income) - (SUM(expenses) + SUM(payments))) / SUM(income) AS Excess\r\nFROM     dbo.View_Totals\r\nWHERE\r\n  DATEFROMPARTS ( year_id, 1, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY \r\n  year_id,\r\n  DATEFROMPARTS ( year_id, 1, 1 )\r\nORDER BY\r\n  time ASC"
    }
   ]
  },
  {
   "title": "Expenses by Type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "repeat": "expense_type",
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( e.year_id, 1, 1 ) as time,\n  SUM(e.amount) as value,\n  '$expense_type' as metric\nFROM\n  dbo.expenses e \n   INNER JOIN \n      dbo.expense_types t \n      ON e.expense_type_id = t.expense_type_pk \nWHERE\n  t.expense_type LIKE '$expense_type' AND DATEFROMPARTS ( e.year_id, 1, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  e.year_id,\n  DATEFROMPARTS ( e.year_id, 1, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Payments by Loan",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( p.year_id, 1, 1 ) as time,\n  SUM(p.amount) as value,\n  '$loan' as metric\nFROM\n  dbo.payments p\n   INNER JOIN \n      dbo.loans l\n      ON p.loan_id = l.loan_pk \nWHERE\n  l.loan_alias LIKE '$loan' AND DATEFROMPARTS ( p.year_id, 1, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  p.year_id,\n  DATEFROMPARTS ( p.year_id, 1, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Payments by Insurance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( p.year_id, 1, 1 ) as time,\n  SUM(p.amount) as value,\n  '$insurance' as metric\nFROM\n  dbo.payments p\n   INNER JOIN \n      dbo.insurance i\n      ON p.insurance_id = i.insurance_pk \nWHERE\n  i.insurance_alias LIKE '$insurance' AND DATEFROMPARTS ( p.year_id, 1, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  p.year_id,\n  DATEFROMPARTS ( p.year_id, 1, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Payments by Tuition",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( p.year_id, 1, 1 ) as time,\n  SUM(p.amount) as value,\n  '$tuition' as metric\nFROM\n  dbo.payments p\n   INNER JOIN \n      dbo.tuition t\n      ON p.tuition_id = t.tuition_pk \nWHERE\n  t.tuition_alias LIKE '$tuition' AND DATEFROMPARTS ( p.year_id, 1, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  p.year_id,\n  DATEFROMPARTS ( p.year_id, 1, 1 )\nORDER BY\n  time ASC"
    }
   ]
  }
 ]
}