{
 "title": "MyBudget - Summary",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  { "title": "Expenses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Gas",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, month_id, 1 ) as time,\n  SUM(amount) as value\nFROM\n  expenses\nWHERE\n  expense_type_id = 10 AND DATEFROMPARTS ( year_id, month_id, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  DATEFROMPARTS ( year_id, month_id, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Garbage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, month_id, 1 ) as time,\n  SUM(amount) as value\nFROM\n  expenses\nWHERE\n  expense_type_id = 4 AND DATEFROMPARTS ( year_id, month_id, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  DATEFROMPARTS ( year_id, month_id, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Groceries",
   "type": "singlestat",
   "description": "Cub, Hyvee, Fresh Thyme",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, month_id, 1 ) as time,\n  SUM(amount) as value\nFROM\n  expenses\nWHERE\n  expense_type_id = 15 AND DATEFROMPARTS ( year_id, month_id, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  DATEFROMPARTS ( year_id, month_id, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Gasoline",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, month_id, 1 ) as time,\n  SUM(amount) as value,\n  'Gasoline' as metric\nFROM\n  expenses\nWHERE\n  expense_type_id = 1 AND DATEFROMPARTS ( year_id, month_id, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  DATEFROMPARTS ( year_id, month_id, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Cable/Dish",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, month_id, 1 ) as time,\n  SUM(amount) as value\nFROM\n  expenses\nWHERE\n  expense_type_id = 13 AND DATEFROMPARTS ( year_id, month_id, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  DATEFROMPARTS ( year_id, month_id, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Auto Care",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, month_id, 1 ) as time,\n  SUM(amount) as value\nFROM\n  expenses\nWHERE\n  expense_type_id = 1002 AND DATEFROMPARTS ( year_id, month_id, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  DATEFROMPARTS ( year_id, month_id, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Total Expenses",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, month_id, 1 ) as time,\n  SUM(amount) as value\nFROM\n  expenses\nWHERE\n  DATEFROMPARTS ( year_id, month_id, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  DATEFROMPARTS ( year_id, month_id, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Electric",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, month_id, 1 ) as time,\n  SUM(amount) as value\nFROM\n  expenses\nWHERE\n  expense_type_id = 2 AND DATEFROMPARTS ( year_id, month_id, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  DATEFROMPARTS ( year_id, month_id, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Internet",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, month_id, 1 ) as time,\n  SUM(amount) as value\nFROM\n  expenses\nWHERE\n  expense_type_id = 14 AND DATEFROMPARTS ( year_id, month_id, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  DATEFROMPARTS ( year_id, month_id, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Household Goods",
   "type": "singlestat",
   "description": "Target, Sam's Club, Walmart",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, month_id, 1 ) as time,\n  SUM(amount) as value\nFROM\n  expenses\nWHERE\n  expense_type_id = 7 AND DATEFROMPARTS ( year_id, month_id, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  DATEFROMPARTS ( year_id, month_id, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Gym Membership",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, month_id, 1 ) as time,\n  SUM(amount) as value\nFROM\n  expenses\nWHERE\n  expense_type_id = 5 AND DATEFROMPARTS ( year_id, month_id, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  DATEFROMPARTS ( year_id, month_id, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Home Phone",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, month_id, 1 ) as time,\n  SUM(amount) as value\nFROM\n  expenses\nWHERE\n  expense_type_id = 12 AND DATEFROMPARTS ( year_id, month_id, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  DATEFROMPARTS ( year_id, month_id, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Daycare",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 3 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, month_id, 1 ) as time,\n  SUM(amount) as value\nFROM\n  expenses\nWHERE\n  expense_type_id = 9 AND DATEFROMPARTS ( year_id, month_id, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  DATEFROMPARTS ( year_id, month_id, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "City Utilities",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, month_id, 1 ) as time,\n  SUM(amount) as value\nFROM\n  expenses\nWHERE\n  expense_type_id = 3 AND DATEFROMPARTS ( year_id, month_id, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  DATEFROMPARTS ( year_id, month_id, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Cell Phones",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, month_id, 1 ) as time,\n  SUM(amount) as value,\n  'Gasoline' as metric\nFROM\n  expenses\nWHERE\n  expense_type_id = 11 AND DATEFROMPARTS ( year_id, month_id, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  DATEFROMPARTS ( year_id, month_id, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Home Improvements",
   "type": "singlestat",
   "description": "Menards, Home Depot, Lowes",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 5 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, month_id, 1 ) as time,\n  SUM(amount) as value\nFROM\n  expenses\nWHERE\n  expense_type_id = 8 AND DATEFROMPARTS ( year_id, month_id, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  DATEFROMPARTS ( year_id, month_id, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Healthcare",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 5 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, month_id, 1 ) as time,\n  SUM(amount) as value\nFROM\n  expenses\nWHERE\n  expense_type_id = 6 AND DATEFROMPARTS ( year_id, month_id, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  DATEFROMPARTS ( year_id, month_id, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  { "title": "Payments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Mortgage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 8 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, month_id, 1 ) as time,\n  SUM(amount) as value\nFROM\n  payments\nWHERE\n  loan_id = 8 AND DATEFROMPARTS ( year_id, month_id, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  DATEFROMPARTS ( year_id, month_id, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Life Insurance (Andy)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 8 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, month_id, 1 ) as time,\n  SUM(amount) as value\nFROM\n  payments\nWHERE\n  insurance_id = 1 AND DATEFROMPARTS ( year_id, month_id, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  DATEFROMPARTS ( year_id, month_id, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Car Insurance (Van)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 8 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, month_id, 1 ) as time,\n  SUM(amount) as value\nFROM\n  payments\nWHERE\n  insurance_id = 7 AND DATEFROMPARTS ( year_id, month_id, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  DATEFROMPARTS ( year_id, month_id, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Total Payments",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, month_id, 1 ) as time,\n  SUM(amount) as value\nFROM\n  payments\nWHERE\n  DATEFROMPARTS ( year_id, month_id, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  DATEFROMPARTS ( year_id, month_id, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Life Insurance (Umbrella)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 10 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, month_id, 1 ) as time,\n  SUM(amount) as value\nFROM\n  payments\nWHERE\n  insurance_id = 8 AND DATEFROMPARTS ( year_id, month_id, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  DATEFROMPARTS ( year_id, month_id, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Life Insurance (Katie)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 10 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, month_id, 1 ) as time,\n  SUM(amount) as value\nFROM\n  payments\nWHERE\n  insurance_id = 2 AND DATEFROMPARTS ( year_id, month_id, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  DATEFROMPARTS ( year_id, month_id, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Car Insurance (Truck)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 10 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, month_id, 1 ) as time,\n  SUM(amount) as value\nFROM\n  payments\nWHERE\n  insurance_id = 9 AND DATEFROMPARTS ( year_id, month_id, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  DATEFROMPARTS ( year_id, month_id, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  { "title": "Income", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Income (Andy)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 14 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, month_id, 1 ) as time,\n  SUM(amount) as value\nFROM\n  income\nWHERE\n  family_member_id = 3 AND DATEFROMPARTS ( year_id, month_id, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  DATEFROMPARTS ( year_id, month_id, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Income (Katie)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 14 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, month_id, 1 ) as time,\n  SUM(amount) as value\nFROM\n  income\nWHERE\n  family_member_id = 4 AND DATEFROMPARTS ( year_id, month_id, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  DATEFROMPARTS ( year_id, month_id, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Total Income",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 14 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  DATEFROMPARTS ( year_id, month_id, 1 ) as time,\n  SUM(amount) as value\nFROM\n  income\nWHERE\n  DATEFROMPARTS ( year_id, month_id, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY \n  DATEFROMPARTS ( year_id, month_id, 1 )\nORDER BY\n  time ASC"
    }
   ]
  },
  {
   "title": "Total Excess",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 16 },
   "format": "currencyUSD",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT DATEFROMPARTS ( year_id, month_id, 1 ) as time,\r\n       SUM(income) - (SUM(expenses) + SUM(payments)) AS Excess\r\nFROM     dbo.View_Totals\r\nWHERE\r\n  DATEFROMPARTS ( year_id, month_id, 1 ) BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY \r\n  DATEFROMPARTS ( year_id, month_id, 1 )\r\nORDER BY\r\n  time ASC"
    }
   ]
  }
 ]
}